### ISSUE TITLE
LoadError when trying to run rspec

### ISSUE THREAD

**Issue by prashcr** [tongueroo/cody#16]
I tried running `rspec`, but I gives me the following `LoadError`. Are there additional setup steps to be done before I can contribute?

```
An error occurred while loading spec_helper. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require "aws_data"

LoadError:
  cannot load such file -- aws_data
# ./lib/cody.rb:11:in `<top (required)>'
# ./spec/spec_helper.rb:17:in `require'
# ./spec/spec_helper.rb:17:in `<top (required)>'
```

**Comment by tongueroo** [comment]
```
git submodule init
git submodule update
```

Should do the trick.
