### ISSUE TITLE
i18n dependency issue

### ISSUE THREAD

**Issue by joelvh** [tongueroo/cody#4]
Hi @tongueroo - saw your YouTube talk going through the various projects you've got. Had come across Ruby on Jets in the past, and finally have some use cases with a serverless architecture to start looking at using what you've built.

I'm looking for a CI/CD solution and Cody seems like the right fit, but the simple setup seems to have an issue on my system. I haven't come across this before.

Running `cody init` gives me `cannot load such file -- i18n/core_ext/string/interpolate (LoadError)`.

Thoughts?

```bash
joels-mbp-2016:rembly-backend Joel$ gem install cody
Fetching: cody-0.7.1.gem (100%)
Successfully installed cody-0.7.1
1 gem installed
joels-mbp-2016:rembly-backend Joel$ cody init
/Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/activesupport-3.1.12/lib/active_support/values/time_zone.rb:270: warning: circular argument reference - now
Traceback (most recent call last):
	21: from /Users/Joel/.rbenv/versions/2.5.6/bin/cody:23:in `<main>'
	20: from /Users/Joel/.rbenv/versions/2.5.6/bin/cody:23:in `load'
	19: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/cody-0.7.1/exe/cody:11:in `<top (required)>'
	18: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	17: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	16: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/cody-0.7.1/lib/cody.rb:13:in `<top (required)>'
	15: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/zeitwerk-2.2.0/lib/zeitwerk/kernel.rb:23:in `require'
	14: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	13: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/cody-0.7.1/vendor/cfn_camelizer/lib/cfn_camelizer.rb:5:in `<top (required)>'
	11: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/zeitwerk-2.2.0/lib/zeitwerk/kernel.rb:23:in `require'
	10: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/activesupport-3.1.12/lib/active_support/core_ext/string.rb:9:in `<top (required)>'
	 7: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/zeitwerk-2.2.0/lib/zeitwerk/kernel.rb:23:in `require'
	 6: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 4: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/activesupport-3.1.12/lib/active_support/core_ext/string/interpolation.rb:2:in `<top (required)>'
	 3: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0/gems/zeitwerk-2.2.0/lib/zeitwerk/kernel.rb:23:in `require'
	 2: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	 1: from /Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/Users/Joel/.rbenv/versions/2.5.6/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- i18n/core_ext/string/interpolate (LoadError)
```

Thanks!

**Comment by joelvh** [comment]
I should mention that Ruby 2.5.6 is a fairly fresh installation because I downgraded for Lambda compatibility. ActiveSupport/Rails are also not a dependency in my project, so any dependencies on that are presumably for Cody.

**Comment by joelvh** [comment]
As I wrote that comment, I saw that by default somehow a really old version of ActiveRecord was installed. I updated that and the command works. However, I get this new error, likely because I don't have default AWS credentials setup? Seems that this is an assumption that isn't noted in the docs, from what I saw.

`missing region; use :region option or export region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)`

Seems Cody assumes some version of Rails is installed and AWS default profile are setup. Please let me know if that's right or something else is going on.

Thanks!

**Comment by tongueroo** [comment]
> RE: Specific version of ActiveSupport required

You’re probably right. Been running the latest, so will probably just make that a requirement in the gemspec

> RE: aws profile setup

Probably also right. Will have to add some docs on the install page. 

Will take a look in time👍

**Comment by tongueroo** [comment]
* Made activesupport ~6+ a requirement
* Added notes about aws cli on the install page
